Fix missing task decorator on allocation expiration warning task
ChameleonCloud/portal pull request #251
Opened 2021-10-07 15:13 UTC by Mark-Powers

2021-10-11 16:50 UTC, super-cooper requested changes
Sorry, 1 thing!

2021-10-11 16:50 UTC, super-cooper commented on allocations/tasks.py
> +@task
Actually, could the task be run at a specific time? The original PR had this decorator:
https://github.com/ChameleonCloud/portal/blob/alloc-expire-warn/allocations/tasks.py#L83

We had specifically set it to only run once per day in the original PR: https://github.com/ChameleonCloud/portal/pull/217

2021-10-11 16:56 UTC, super-cooper approved these changes
Whoops!

2021-10-11 16:56 UTC, super-cooper commented on allocations/tasks.py
> +@task
nvm

2021-10-12 14:07 UTC, zhenz approved these changes
:thumbsup:

2021-10-12 14:14 UTC, merged