[trovi] add unique users metric
ChameleonCloud/portal pull request #339
Opened 2022-09-12 14:28 UTC by zhenz

2022-09-12 18:51 UTC, super-cooper approved these changes
I really love the new icons!! I also love that there are tool tips now!!!!!

But I wonder if we can have a more descriptive tool tip than "users"? I can't think of one though.

2022-09-14 14:38 UTC, Mark-Powers requested changes
See the comment about adding the tooltip info so it matches the rest of the site.

I also think we should use phrases for each of these, instead of single words, maybe "Total launches", "Total users" or "Unique users", and then "Number of versions"?

2022-09-14 14:38 UTC, Mark-Powers commented on sharing_portal/templates/sharing_portal/includes/stats.html
> +    <span title="launches"><i class="fa fa-rocket"></i>
We should use the bootstrap `tooltip` field. Here is the example of how we use it for the private icon. This way it'll have a nicer looking popup.

```
<i class="fa fa-eye-slash artifactDetailPrivate" data-toggle="tooltip" data-placement="top" title="This artifact is only visible for those chosen by the author"></i>
```

2022-09-26 18:15 UTC, Mark-Powers approved these changes

2022-10-03 17:43 UTC, merged