Feedback button which redirects to github issues
ChameleonCloud/portal pull request #410
Opened 2023-08-08 21:54 UTC by AnishReddyRavula

This is when artifact contains github url

![image](https://github.com/ChameleonCloud/portal/assets/20154899/0bc7b342-e9e6-45f9-b7ce-716b58ad47de)

2023-08-08 22:19 UTC, super-cooper requested changes
Seems fine to me as long as we're cool with them getting a 404 on certain repos. I believe we already had that discussions.

Requesting changes because there is a critical bug, but other than that I approve.

2023-08-08 22:19 UTC, super-cooper commented on sharing_portal/views.py
> +        "feedback_url": feedback_url,
This will be an unresolved symbol if the artifact doesn't use git.

2023-08-08 22:20 UTC, super-cooper commented
Also, in theory, an artifact can use different git repos for different versions. Are we cool always taking the first one?

2023-08-09 18:27 UTC, super-cooper approved these changes

2023-08-10 15:50 UTC, Mark-Powers requested changes
We need to be a bit cleverer about parsing the version url.

2023-08-10 15:50 UTC, Mark-Powers commented on sharing_portal/views.py
> +        feedback_url = git_content[0]["remote"].replace(".git", "/issues")
This should explicitly check for github, and may need to extract the username/repo name to be correct, as the url might be `git://` too. For trovi, we use a library to do so: https://github.com/ChameleonCloud/trovi/blob/main/trovi/storage/backends/git.py#L57

2023-08-15 14:05 UTC, Mark-Powers approved these changes
This looks great! I like the tests too! Did the tests require any special configuration to run? If so, it would be useful to add a short section to the readme with instructions.

2023-08-15 15:35 UTC, merged